// This file was autogenerated by ../../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../owntra/owntra/game.js', ['owntra.Game'], ['owntra.Player']);
goog.addDependency('../../../owntra/owntra/player.js', ['owntra.Player'], []);
